#
# TFGuilds - Configuration
#

server:
  # Log guild chat to console?
  guild_chat_logging: true

  # Enable guild tags globally?
  guild_tags_enabled: true

# MySQL configuration
mysql:
  host: localhost
  port: 3306
  username: root
  password: password
  database: TFGuilds