name: TFGuilds
version: ${project.version}
main: me.totalfreedom.tfguilds.TFGuilds
api-version: 1.16
softdepend: [TotalFreedomMod]
authors: [speed, super]
description: A guilds plugin for the TotalFreedom server.
commands:
  guild:
    description: The main command of TFGuilds.
    usage: /<command> [list [guild] | help | create <name> | disband [name] | invite <player> | addmod <guild <player> | player> | removemod <guild <name> | name> | createrole <name> | setowner <guild <player> | player> | kick <guild <player> | player> | leave | setstate <guild <state> | state> | tp <player> | info [guild] | tag <set <tag> | clear> | join <guild> | chat [message] | saveconfig]
    aliases: [g]
  guildchat:
    description: Talk in chat with your guild.
    usage: /<command> [message]
    aliases: [gchat, gc]
  tfguilds:
    description: Information about the plugin.
    usage: /<command>
    aliases: [tfg]