name: TFGuilds
version: ${project.version}
main: me.totalfreedom.tfguilds.TFGuilds
api-version: 1.16
authors: [speed, super]
description: A guilds plugin for the TotalFreedom server.
commands:
  guild:
    description: The main command of TFGuilds.
    usage: /<command> [list | help | create <name> | disband [name] | invite <player> | addmod <guild <player> | player> | removemod <guild <name> | name> | createrank <name> | setowner <guild <player> | player> | kick <guild <player> | player> | leave | setstate <guild <state> | state> | tp <player> | info [guild | player] | tag <set <tag> | clear> | join <guild> | chat [message] | roster [guild] | rename <name> | createrank <name> | deleterank <rank> | setrank <player> <rank | none> motd <set <motd> | clear> | home [set] | chat [message] | setdefaultrank <rank | none> | toggletags]
    aliases: [g]
  guildchat:
    description: Talk in chat with your guild.
    usage: /<command> [message]
    aliases: [gchat]
  tfguilds:
    description: Information about the plugin.
    usage: /<command>
    aliases: [tfg]
  guildchatspy:
    description: An admin only command which allows for spying on guild chat.
    usage: /<command>
    aliases: [gchatspy, gcs]